server:
  port: 8085

dhan:
  base-url: https://api.dhan.co
  access-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJkaGFuIiwicGFydG5lcklkIjoiIiwiZXhwIjoxNzc1MTgyODYzLCJpYXQiOjE3NzUwOTY0NjMsInRva2VuQ29uc3VtZXJUeXBlIjoiU0VMRiIsIndlYmhvb2tVcmwiOiIiLCJkaGFuQ2xpZW50SWQiOiIxMTA2Mjg5ODAzIn0.UfyLv0XiOrFU4rbzJzh49lj600n2R4L9e7R8S8fJMo3VCyHZ-WC4qoNaTTehJd0YKnDRIdiuGTVJ22XjBFyeyg
  client-id: 1106289803
  api-key: 456cb2f8
  api-secret: a772ba45-7574-4262-a42f-5da13a1bbf88

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: anupam@2026
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # creates tables automatically
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    serialization:
      INDENT_OUTPUT: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
