server:
  port: 8085

dhan:
  base-url: https://api.dhan.co
  access-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJkaGFuIiwicGFydG5lcklkIjoiIiwiZXhwIjoxNzY4MTMxMDkxLCJpYXQiOjE3NjgwNDQ2OTEsInRva2VuQ29uc3VtZXJUeXBlIjoiU0VMRiIsIndlYmhvb2tVcmwiOiIiLCJkaGFuQ2xpZW50SWQiOiIxMTA2Mjg5ODAzIn0.4ZGSyF01CZSYchwIQO1chzuIivWjAm4GSfsfMPNtlrhJL2NxyK-RayWTXaXBEym5zdLb5MKFyB_wpXv9qd4nKQ
  client-id: 1106289803
